DROP TABLE temporarynuts;
CREATE TABLE temporarynuts (
  id int(11) NOT NULL,
  textincludingunits varchar(255) NOT NULL,
  template varchar(255) NOT NULL,
  unittext varchar(255),
)

DELETE FROM temporarynuts;
INSERT INTO temporarynuts SET id=1, textincludingunits="15mg (11 % av DRI)  ", template="__ZUANTITY____UNIT__ (11 % av DRI)  ", unittext="mg";
INSERT INTO temporarynuts SET id=2, textincludingunits="1g.  ", template="__ZUANTITY____UNIT__.  ", unittext="g";
INSERT INTO temporarynuts SET id=3, textincludingunits="6 g  ", template="__ZUANTITY__ __UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=4, textincludingunits="8g  ", template="__ZUANTITY____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=5, textincludingunits=" används ej __QUANTITY__ Gram", template=" används ej __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=6, textincludingunits="Biotin __QUANTITY__ Mikrogram", template="Biotin __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=7, textincludingunits="CHO- __QUANTITY__ Gram", template="CHO- __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=8, textincludingunits="*Dagligt Referensintag  ", template="*Dagligt Referensintag  ", unittext="";
INSERT INTO temporarynuts SET id=9, textincludingunits="*Dagligt Referens Intag  ", template="*Dagligt Referens Intag  ", unittext="";
INSERT INTO temporarynuts SET id=10, textincludingunits="__DELETED__", template="__DELETED__", unittext="";
INSERT INTO temporarynuts SET id=11, textincludingunits="Energi __QUANTITY__ Gram", template="Energi __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=12, textincludingunits="Energi __QUANTITY__ kcal", template="Energi __QUANTITY__ __UNIT__", unittext="kcal";
INSERT INTO temporarynuts SET id=13, textincludingunits="energi __QUANTITY__ kilojoule", template="energi __QUANTITY__ __UNIT__", unittext="kilojoule";
INSERT INTO temporarynuts SET id=14, textincludingunits="Energi __QUANTITY__ Kilojoule", template="Energi __QUANTITY__ __UNIT__", unittext="Kilojoule";
INSERT INTO temporarynuts SET id=15, textincludingunits="Energi __QUANTITY__ Kilokalori", template="Energi __QUANTITY__ __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=16, textincludingunits="energi __QUANTITY__ kilokalorier", template="energi __QUANTITY__ __UNIT__", unittext="kilokalorier";
INSERT INTO temporarynuts SET id=17, textincludingunits="Energi __QUANTITY__ kJ", template="Energi __QUANTITY__ __UNIT__", unittext="kJ";
INSERT INTO temporarynuts SET id=18, textincludingunits="Energi __QUANTITY__ Milligram", template="Energi __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=19, textincludingunits="Energi __ZUANTITY_RANGE__ Kilojoule", template="Energi __ZUANTITY_RANGE__ __UNIT__", unittext="Kilojoule";
INSERT INTO temporarynuts SET id=20, textincludingunits="Energi __ZUANTITY_RANGE__ Kilokalori", template="Energi __ZUANTITY_RANGE__ __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=21, textincludingunits="Energivärde: __QUANTITY__ kcal", template="Energivärde: __QUANTITY__ __UNIT__", unittext="kcal";
INSERT INTO temporarynuts SET id=22, textincludingunits="Energivärde: __QUANTITY__ kJ", template="Energivärde: __QUANTITY__ __UNIT__", unittext="kJ";
INSERT INTO temporarynuts SET id=23, textincludingunits="Fett34 g  ", template="Fett34 __UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=24, textincludingunits="Fett __QUANTITY__ g", template="Fett __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=25, textincludingunits="Fett __QUANTITY__g  ", template="Fett __QUANTITY____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=26, textincludingunits="fett __QUANTITY__ gram", template="fett __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=27, textincludingunits="Fett __QUANTITY__ Gram", template="Fett __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=28, textincludingunits="Fett __QUANTITY__ Kilokalori", template="Fett __QUANTITY__ __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=29, textincludingunits="Fett __QUANTITY__ Mikrogram", template="Fett __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=30, textincludingunits="Fiber __QUANTITY__g  ", template="Fiber __QUANTITY____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=31, textincludingunits="fiber __QUANTITY__ gram", template="fiber __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=32, textincludingunits="Fiber __QUANTITY__ Gram", template="Fiber __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=33, textincludingunits="fleromättat fett __QUANTITY__ g", template="fleromättat fett __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=34, textincludingunits="Fluorid __QUANTITY__ Milligram", template="Fluorid __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=35, textincludingunits="Folsyra __QUANTITY__ g", template="Folsyra __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=36, textincludingunits="Folsyra __QUANTITY__ Mikrogram", template="Folsyra __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=37, textincludingunits="Fosfor __QUANTITY__ mg", template="Fosfor __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=38, textincludingunits="Fosfor __QUANTITY__ Milligram", template="Fosfor __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=39, textincludingunits="Järn __QUANTITY__ Gram", template="Järn __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=40, textincludingunits="Järn __QUANTITY__ Milligram", template="Järn __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=41, textincludingunits="Jod __QUANTITY__ g", template="Jod __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=42, textincludingunits="Jod __QUANTITY__ Mikrogram", template="Jod __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=43, textincludingunits="Jod __QUANTITY__ Milligram", template="Jod __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=44, textincludingunits="Jordgubb/VaniljEnergi __QUANTITY__ kJ/80", template="Jordgubb/VaniljEnergi __QUANTITY__ __UNIT__/80", unittext="kJ";
INSERT INTO temporarynuts SET id=45, textincludingunits="Kalcium __QUANTITY__ mg", template="Kalcium __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=46, textincludingunits="Kalcium __QUANTITY__ Milligram", template="Kalcium __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=47, textincludingunits="Kalium __QUANTITY__ mg", template="Kalium __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=48, textincludingunits="Kalium __QUANTITY__ Milligram", template="Kalium __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=49, textincludingunits="Klorid __QUANTITY__ mg", template="Klorid __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=50, textincludingunits="Klorid __QUANTITY__ Milligram", template="Klorid __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=51, textincludingunits="Kolhydrat11 g  ", template="Kolhydrat11 __UNIT__  ", unittext="";
INSERT INTO temporarynuts SET id=52, textincludingunits="Kolhydrater __QUANTITY__ g", template="Kolhydrater __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=53, textincludingunits="Kolhydrater __QUANTITY__g  ", template="Kolhydrater __QUANTITY____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=54, textincludingunits="Kolhydrat __QUANTITY__ g", template="Kolhydrat __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=55, textincludingunits="kolhydrat __QUANTITY__ gram", template="kolhydrat __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=56, textincludingunits="Kolhydrat __QUANTITY__ Gram", template="Kolhydrat __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=57, textincludingunits="Koppar __QUANTITY__ Kilokalori", template="Koppar __QUANTITY__ __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=58, textincludingunits="Koppar __QUANTITY__ Mikrogram", template="Koppar __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=59, textincludingunits="Koppar __QUANTITY__ Milligram", template="Koppar __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=60, textincludingunits="Krom __QUANTITY__ Mikrogram", template="Krom __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=61, textincludingunits="Magnesium __QUANTITY__ Milligram", template="Magnesium __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=62, textincludingunits="Mangan __QUANTITY__ Milligram", template="Mangan __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=63, textincludingunits="Molybden __QUANTITY__ g", template="Molybden __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=64, textincludingunits="Molybden __QUANTITY__ Mikrogram", template="Molybden __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=65, textincludingunits="NACL __QUANTITY__ Gram", template="NACL __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=66, textincludingunits="NACL __QUANTITY__ Milligram", template="NACL __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=67, textincludingunits="Natrium __QUANTITY__ Gram", template="Natrium __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=68, textincludingunits="Natrium __QUANTITY__ Milligram", template="Natrium __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=69, textincludingunits="Niacin __QUANTITY__ Milligram", template="Niacin __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=70, textincludingunits="Pantotensyra __QUANTITY__ mg", template="Pantotensyra __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=71, textincludingunits="Pantotensyra __QUANTITY__ Milligram", template="Pantotensyra __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=72, textincludingunits="Protein __QUANTITY__ g", template="Protein __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=73, textincludingunits="Protein __QUANTITY__g  ", template="Protein __QUANTITY____UNIT__  ", unittext="";
INSERT INTO temporarynuts SET id=74, textincludingunits="protein __QUANTITY__ gram", template="protein __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=75, textincludingunits="Protein __QUANTITY__ Gram", template="Protein __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=76, textincludingunits="Riboflavin __QUANTITY__", template="Riboflavin __QUANTITY__", unittext="";
INSERT INTO temporarynuts SET id=77, textincludingunits="Riboflavin __QUANTITY__ mg", template="Riboflavin __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=78, textincludingunits="Riboflavin __QUANTITY__ Milligram", template="Riboflavin __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=79, textincludingunits="Salt", template="Salt", unittext="";
INSERT INTO temporarynuts SET id=80, textincludingunits="Salt <0", template="Salt <0", unittext="";
INSERT INTO temporarynuts SET id=81, textincludingunits="Salt __QUANTITY__ g", template="Salt __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=82, textincludingunits="Salt __QUANTITY__g  ", template="Salt __QUANTITY____UNIT__  ", unittext="";
INSERT INTO temporarynuts SET id=83, textincludingunits="salt __QUANTITY__ gram", template="salt __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=84, textincludingunits="Salt __QUANTITY__ Gram", template="Salt __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=85, textincludingunits="Selen __QUANTITY__ Mikrogram", template="Selen __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=86, textincludingunits="Tiamin __QUANTITY__ Milligram", template="Tiamin __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=87, textincludingunits="varav enkelomättat fett __QUANTITY__ g", template="varav enkelomättat fett __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=88, textincludingunits="Varav enkelomättat fett __QUANTITY__ Gram", template="Varav enkelomättat fett __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=89, textincludingunits="varav fleromättat fett __QUANTITY__ g", template="varav fleromättat fett __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=90, textincludingunits="Varav fleromättat fett __QUANTITY__ Gram", template="Varav fleromättat fett __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=91, textincludingunits="varav laktos __QUANTITY__ g", template="varav laktos __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=92, textincludingunits="varav mättat fett __QUANTITY__ g", template="varav mättat fett __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=93, textincludingunits="varav: Mättat fett __QUANTITY__g  ", template="varav: Mättat fett __QUANTITY____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=94, textincludingunits="varav mättat fett __QUANTITY__ gram", template="varav mättat fett __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=95, textincludingunits="Varav mättat fett __QUANTITY__ Gram", template="Varav mättat fett __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=96, textincludingunits="varav polyoler __QUANTITY__ gram", template="varav polyoler __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=97, textincludingunits="Varav polyoler __QUANTITY__ Gram", template="Varav polyoler __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=98, textincludingunits="Varav sockerarter", template="Varav sockerarter", unittext="";
INSERT INTO temporarynuts SET id=99, textincludingunits="varav sockerarter2", template="varav sockerarter2", unittext="";
INSERT INTO temporarynuts SET id=100, textincludingunits="varav sockerarter __QUANTITY__", template="varav sockerarter __QUANTITY__", unittext="";
INSERT INTO temporarynuts SET id=101, textincludingunits="varav sockerarter __QUANTITY__ g", template="varav sockerarter __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=102, textincludingunits="varav: Sockerarter __QUANTITY__g  ", template="varav: Sockerarter __QUANTITY____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=103, textincludingunits="varav sockerarter __QUANTITY__ gram", template="varav sockerarter __QUANTITY__ __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=104, textincludingunits="Varav sockerarter __QUANTITY__ Gram", template="Varav sockerarter __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=105, textincludingunits="varav sockerater __QUANTITY__ g", template="varav sockerater __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=106, textincludingunits="Varav stärkelse __QUANTITY__ Gram", template="Varav stärkelse __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=107, textincludingunits="Vitamin A__ZUANTITY__ µg (39% av DRI*) *Dagligt Referensintag  ", template="Vitamin A310 __UNIT__ (39% av DRI*) *Dagligt Referensintag  ", unittext="µg";
INSERT INTO temporarynuts SET id=108, textincludingunits="Vitamin A __QUANTITY__ g", template="Vitamin A __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=109, textincludingunits="Vitamin A __QUANTITY__ Mikrogram", template="Vitamin A __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=110, textincludingunits="Vitamin B12 __QUANTITY__ g", template="Vitamin B12 __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=111, textincludingunits="Vitamin B12 __QUANTITY__ mg", template="Vitamin B12 __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=112, textincludingunits="Vitamin B12 __QUANTITY__ Mikrogram", template="Vitamin B12 __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=113, textincludingunits="Vitamin B6 __QUANTITY__ Milligram", template="Vitamin B6 __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=114, textincludingunits="Vitamin C __QUANTITY__ mg", template="Vitamin C __QUANTITY__ __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=115, textincludingunits="Vitamin C __QUANTITY__ Milligram", template="Vitamin C __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=116, textincludingunits="Vitamin D __QUANTITY__ g", template="Vitamin D __QUANTITY__ __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=117, textincludingunits="Vitamin D __QUANTITY__ Gram", template="Vitamin D __QUANTITY__ __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=118, textincludingunits="Vitamin D __QUANTITY__ Mikrogram", template="Vitamin D __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=119, textincludingunits="Vitamin E __QUANTITY__ Milligram", template="Vitamin E __QUANTITY__ __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=120, textincludingunits="Vitamin K __QUANTITY__ Mikrogram", template="Vitamin K __QUANTITY__ __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=121, textincludingunits="Zink __QUANTITY__ Milligram", template="Zink __QUANTITY__ __UNIT__", unittext="Milligram";
