DROP TABLE temporarynuts;
CREATE TABLE temporarynuts (
  id int(11) NOT NULL,
  textincludingunits varchar(255) NOT NULL,
  template varchar(255) NOT NULL,
  unittext varchar(255),
)

DELETE FROM temporarynuts;
INSERT INTO temporarynuts SET id=1, textincludingunits="15mg (11 % av DRI)  ", template="__QUANT____UNIT__ (11 % av DRI)  ", unittext="mg";
INSERT INTO temporarynuts SET id=2, textincludingunits="1g.  ", template="__QUANT____UNIT__.  ", unittext="g";
INSERT INTO temporarynuts SET id=3, textincludingunits="6 g  ", template="__QUANT__ __UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=4, textincludingunits="8g  ", template="__QUANT____UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=5, textincludingunits=" används ej QUANTITY Gram", template=" används ej QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=6, textincludingunits="Biotin QUANTITY Mikrogram", template="Biotin QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=7, textincludingunits="CHO- QUANTITY Gram", template="CHO- QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=8, textincludingunits="*Dagligt Referensintag  ", template="*Dagligt Referensintag  ", unittext="";
INSERT INTO temporarynuts SET id=9, textincludingunits="*Dagligt Referens Intag  ", template="*Dagligt Referens Intag  ", unittext="";
INSERT INTO temporarynuts SET id=10, textincludingunits="__DELETED__", template="__DELETED__", unittext="";
INSERT INTO temporarynuts SET id=11, textincludingunits="Energi QUANTITY Gram", template="Energi QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=12, textincludingunits="Energi QUANTITY kcal", template="Energi QUANTITY __UNIT__", unittext="kcal";
INSERT INTO temporarynuts SET id=13, textincludingunits="energi QUANTITY kilojoule", template="energi QUANTITY __UNIT__", unittext="kilojoule";
INSERT INTO temporarynuts SET id=14, textincludingunits="Energi QUANTITY Kilojoule", template="Energi QUANTITY __UNIT__", unittext="Kilojoule";
INSERT INTO temporarynuts SET id=15, textincludingunits="Energi QUANTITY Kilokalori", template="Energi QUANTITY __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=16, textincludingunits="energi QUANTITY kilokalorier", template="energi QUANTITY __UNIT__", unittext="kilokalorier";
INSERT INTO temporarynuts SET id=17, textincludingunits="Energi QUANTITY kJ", template="Energi QUANTITY __UNIT__", unittext="kJ";
INSERT INTO temporarynuts SET id=18, textincludingunits="Energi QUANTITY Milligram", template="Energi QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=19, textincludingunits="Energi QUANTITY_RANGE Kilojoule", template="Energi QUANTITY_RANGE __UNIT__", unittext="Kilojoule";
INSERT INTO temporarynuts SET id=20, textincludingunits="Energi QUANTITY_RANGE Kilokalori", template="Energi QUANTITY_RANGE __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=21, textincludingunits="Energivärde: QUANTITY kcal", template="Energivärde: QUANTITY __UNIT__", unittext="kcal";
INSERT INTO temporarynuts SET id=22, textincludingunits="Energivärde: QUANTITY kJ", template="Energivärde: QUANTITY __UNIT__", unittext="kJ";
INSERT INTO temporarynuts SET id=23, textincludingunits="Fett34 g  ", template="Fett34 __UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=24, textincludingunits="Fett QUANTITY g", template="Fett QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=25, textincludingunits="Fett QUANTITYg  ", template="Fett QUANTITY__UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=26, textincludingunits="fett QUANTITY gram", template="fett QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=27, textincludingunits="Fett QUANTITY Gram", template="Fett QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=28, textincludingunits="Fett QUANTITY Kilokalori", template="Fett QUANTITY __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=29, textincludingunits="Fett QUANTITY Mikrogram", template="Fett QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=30, textincludingunits="Fiber QUANTITYg  ", template="Fiber QUANTITY__UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=31, textincludingunits="fiber QUANTITY gram", template="fiber QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=32, textincludingunits="Fiber QUANTITY Gram", template="Fiber QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=33, textincludingunits="fleromättat fett QUANTITY g", template="fleromättat fett QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=34, textincludingunits="Fluorid QUANTITY Milligram", template="Fluorid QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=35, textincludingunits="Folsyra QUANTITY g", template="Folsyra QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=36, textincludingunits="Folsyra QUANTITY Mikrogram", template="Folsyra QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=37, textincludingunits="Fosfor QUANTITY mg", template="Fosfor QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=38, textincludingunits="Fosfor QUANTITY Milligram", template="Fosfor QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=39, textincludingunits="Järn QUANTITY Gram", template="Järn QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=40, textincludingunits="Järn QUANTITY Milligram", template="Järn QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=41, textincludingunits="Jod QUANTITY g", template="Jod QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=42, textincludingunits="Jod QUANTITY Mikrogram", template="Jod QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=43, textincludingunits="Jod QUANTITY Milligram", template="Jod QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=44, textincludingunits="Jordgubb/VaniljEnergi QUANTITY kJ/80", template="Jordgubb/VaniljEnergi QUANTITY __UNIT__/80", unittext="kJ";
INSERT INTO temporarynuts SET id=45, textincludingunits="Kalcium QUANTITY mg", template="Kalcium QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=46, textincludingunits="Kalcium QUANTITY Milligram", template="Kalcium QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=47, textincludingunits="Kalium QUANTITY mg", template="Kalium QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=48, textincludingunits="Kalium QUANTITY Milligram", template="Kalium QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=49, textincludingunits="Klorid QUANTITY mg", template="Klorid QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=50, textincludingunits="Klorid QUANTITY Milligram", template="Klorid QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=51, textincludingunits="Kolhydrat11 g  ", template="Kolhydrat11 __UNIT__  ", unittext="";
INSERT INTO temporarynuts SET id=52, textincludingunits="Kolhydrater QUANTITY g", template="Kolhydrater QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=53, textincludingunits="Kolhydrater QUANTITYg  ", template="Kolhydrater QUANTITY__UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=54, textincludingunits="Kolhydrat QUANTITY g", template="Kolhydrat QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=55, textincludingunits="kolhydrat QUANTITY gram", template="kolhydrat QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=56, textincludingunits="Kolhydrat QUANTITY Gram", template="Kolhydrat QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=57, textincludingunits="Koppar QUANTITY Kilokalori", template="Koppar QUANTITY __UNIT__", unittext="Kilokalori";
INSERT INTO temporarynuts SET id=58, textincludingunits="Koppar QUANTITY Mikrogram", template="Koppar QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=59, textincludingunits="Koppar QUANTITY Milligram", template="Koppar QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=60, textincludingunits="Krom QUANTITY Mikrogram", template="Krom QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=61, textincludingunits="Magnesium QUANTITY Milligram", template="Magnesium QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=62, textincludingunits="Mangan QUANTITY Milligram", template="Mangan QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=63, textincludingunits="Molybden QUANTITY g", template="Molybden QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=64, textincludingunits="Molybden QUANTITY Mikrogram", template="Molybden QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=65, textincludingunits="NACL QUANTITY Gram", template="NACL QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=66, textincludingunits="NACL QUANTITY Milligram", template="NACL QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=67, textincludingunits="Natrium QUANTITY Gram", template="Natrium QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=68, textincludingunits="Natrium QUANTITY Milligram", template="Natrium QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=69, textincludingunits="Niacin QUANTITY Milligram", template="Niacin QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=70, textincludingunits="Pantotensyra QUANTITY mg", template="Pantotensyra QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=71, textincludingunits="Pantotensyra QUANTITY Milligram", template="Pantotensyra QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=72, textincludingunits="Protein QUANTITY g", template="Protein QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=73, textincludingunits="Protein QUANTITYg  ", template="Protein QUANTITY__UNIT__  ", unittext="";
INSERT INTO temporarynuts SET id=74, textincludingunits="protein QUANTITY gram", template="protein QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=75, textincludingunits="Protein QUANTITY Gram", template="Protein QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=76, textincludingunits="Riboflavin QUANTITY", template="Riboflavin QUANTITY", unittext="";
INSERT INTO temporarynuts SET id=77, textincludingunits="Riboflavin QUANTITY mg", template="Riboflavin QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=78, textincludingunits="Riboflavin QUANTITY Milligram", template="Riboflavin QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=79, textincludingunits="Salt", template="Salt", unittext="";
INSERT INTO temporarynuts SET id=80, textincludingunits="Salt <0", template="Salt <0", unittext="";
INSERT INTO temporarynuts SET id=81, textincludingunits="Salt QUANTITY g", template="Salt QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=82, textincludingunits="Salt QUANTITYg  ", template="Salt QUANTITY__UNIT__  ", unittext="";
INSERT INTO temporarynuts SET id=83, textincludingunits="salt QUANTITY gram", template="salt QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=84, textincludingunits="Salt QUANTITY Gram", template="Salt QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=85, textincludingunits="Selen QUANTITY Mikrogram", template="Selen QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=86, textincludingunits="Tiamin QUANTITY Milligram", template="Tiamin QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=87, textincludingunits="varav enkelomättat fett QUANTITY g", template="varav enkelomättat fett QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=88, textincludingunits="Varav enkelomättat fett QUANTITY Gram", template="Varav enkelomättat fett QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=89, textincludingunits="varav fleromättat fett QUANTITY g", template="varav fleromättat fett QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=90, textincludingunits="Varav fleromättat fett QUANTITY Gram", template="Varav fleromättat fett QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=91, textincludingunits="varav laktos QUANTITY g", template="varav laktos QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=92, textincludingunits="varav mättat fett QUANTITY g", template="varav mättat fett QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=93, textincludingunits="varav: Mättat fett QUANTITYg  ", template="varav: Mättat fett QUANTITY__UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=94, textincludingunits="varav mättat fett QUANTITY gram", template="varav mättat fett QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=95, textincludingunits="Varav mättat fett QUANTITY Gram", template="Varav mättat fett QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=96, textincludingunits="varav polyoler QUANTITY gram", template="varav polyoler QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=97, textincludingunits="Varav polyoler QUANTITY Gram", template="Varav polyoler QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=98, textincludingunits="Varav sockerarter", template="Varav sockerarter", unittext="";
INSERT INTO temporarynuts SET id=99, textincludingunits="varav sockerarter2", template="varav sockerarter2", unittext="";
INSERT INTO temporarynuts SET id=100, textincludingunits="varav sockerarter QUANTITY", template="varav sockerarter QUANTITY", unittext="";
INSERT INTO temporarynuts SET id=101, textincludingunits="varav sockerarter QUANTITY g", template="varav sockerarter QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=102, textincludingunits="varav: Sockerarter QUANTITYg  ", template="varav: Sockerarter QUANTITY__UNIT__  ", unittext="g";
INSERT INTO temporarynuts SET id=103, textincludingunits="varav sockerarter QUANTITY gram", template="varav sockerarter QUANTITY __UNIT__", unittext="gram";
INSERT INTO temporarynuts SET id=104, textincludingunits="Varav sockerarter QUANTITY Gram", template="Varav sockerarter QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=105, textincludingunits="varav sockerater QUANTITY g", template="varav sockerater QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=106, textincludingunits="Varav stärkelse QUANTITY Gram", template="Varav stärkelse QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=107, textincludingunits="Vitamin A310 µg (39% av DRI*) *Dagligt Referensintag  ", template="Vitamin A310 __UNIT__ (39% av DRI*) *Dagligt Referensintag  ", unittext="µg";
INSERT INTO temporarynuts SET id=108, textincludingunits="Vitamin A QUANTITY g", template="Vitamin A QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=109, textincludingunits="Vitamin A QUANTITY Mikrogram", template="Vitamin A QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=110, textincludingunits="Vitamin B12 QUANTITY g", template="Vitamin B12 QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=111, textincludingunits="Vitamin B12 QUANTITY mg", template="Vitamin B12 QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=112, textincludingunits="Vitamin B12 QUANTITY Mikrogram", template="Vitamin B12 QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=113, textincludingunits="Vitamin B6 QUANTITY Milligram", template="Vitamin B6 QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=114, textincludingunits="Vitamin C QUANTITY mg", template="Vitamin C QUANTITY __UNIT__", unittext="mg";
INSERT INTO temporarynuts SET id=115, textincludingunits="Vitamin C QUANTITY Milligram", template="Vitamin C QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=116, textincludingunits="Vitamin D QUANTITY g", template="Vitamin D QUANTITY __UNIT__", unittext="g";
INSERT INTO temporarynuts SET id=117, textincludingunits="Vitamin D QUANTITY Gram", template="Vitamin D QUANTITY __UNIT__", unittext="Gram";
INSERT INTO temporarynuts SET id=118, textincludingunits="Vitamin D QUANTITY Mikrogram", template="Vitamin D QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=119, textincludingunits="Vitamin E QUANTITY Milligram", template="Vitamin E QUANTITY __UNIT__", unittext="Milligram";
INSERT INTO temporarynuts SET id=120, textincludingunits="Vitamin K QUANTITY Mikrogram", template="Vitamin K QUANTITY __UNIT__", unittext="Mikrogram";
INSERT INTO temporarynuts SET id=121, textincludingunits="Zink QUANTITY Milligram", template="Zink QUANTITY __UNIT__", unittext="Milligram";
