UPDATE temporarynuts2 SET scantemplateincludingunits = "scantemplate" WHERE id = 0;
UPDATE temporarynuts2 SET scantemplateincludingunits = "%fmg (11 % av DRI)  " WHERE id = 1;
UPDATE temporarynuts2 SET scantemplateincludingunits = "%fg.  " WHERE id = 2;
UPDATE temporarynuts2 SET scantemplateincludingunits = "%f g  " WHERE id = 3;
UPDATE temporarynuts2 SET scantemplateincludingunits = "%fg  " WHERE id = 4;
UPDATE temporarynuts2 SET scantemplateincludingunits = " används ej %f Gram" WHERE id = 5;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Biotin %f Mikrogram" WHERE id = 6;
UPDATE temporarynuts2 SET scantemplateincludingunits = "CHO- %f Gram" WHERE id = 7;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 8;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 9;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 10;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f Gram" WHERE id = 11;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f kcal" WHERE id = 12;
UPDATE temporarynuts2 SET scantemplateincludingunits = "energi %f kilojoule" WHERE id = 13;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f Kilojoule" WHERE id = 14;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f Kilokalori" WHERE id = 15;
UPDATE temporarynuts2 SET scantemplateincludingunits = "energi %f kilokalorier" WHERE id = 16;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f kJ" WHERE id = 17;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f Milligram" WHERE id = 18;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f|PIM_MULTIVALUE_SEPARATOR|%f Kilojoule" WHERE id = 19;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energi %f|PIM_MULTIVALUE_SEPARATOR|%f Kilokalori" WHERE id = 20;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energivärde: %f kcal" WHERE id = 21;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Energivärde: %f kJ" WHERE id = 22;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fett%f g  " WHERE id = 23;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fett %f g" WHERE id = 24;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fett %fg  " WHERE id = 25;
UPDATE temporarynuts2 SET scantemplateincludingunits = "fett %f gram" WHERE id = 26;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fett %f Gram" WHERE id = 27;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fett %f Kilokalori" WHERE id = 28;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fett %f Mikrogram" WHERE id = 29;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fiber %fg  " WHERE id = 30;
UPDATE temporarynuts2 SET scantemplateincludingunits = "fiber %f gram" WHERE id = 31;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fiber %f Gram" WHERE id = 32;
UPDATE temporarynuts2 SET scantemplateincludingunits = "fleromättat fett %f g" WHERE id = 33;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fluorid %f Milligram" WHERE id = 34;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Folsyra %f g" WHERE id = 35;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Folsyra %f Mikrogram" WHERE id = 36;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fosfor %f mg" WHERE id = 37;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Fosfor %f Milligram" WHERE id = 38;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Järn %f Gram" WHERE id = 39;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Järn %f Milligram" WHERE id = 40;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Jod %f g" WHERE id = 41;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Jod %f Mikrogram" WHERE id = 42;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Jod %f Milligram" WHERE id = 43;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Jordgubb/VaniljEnergi %f kJ/80" WHERE id = 44;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kalcium %f mg" WHERE id = 45;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kalcium %f Milligram" WHERE id = 46;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kalium %f mg" WHERE id = 47;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kalium %f Milligram" WHERE id = 48;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Klorid %f mg" WHERE id = 49;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Klorid %f Milligram" WHERE id = 50;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 51;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kolhydrater %f g" WHERE id = 52;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kolhydrater %fg  " WHERE id = 53;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kolhydrat %f g" WHERE id = 54;
UPDATE temporarynuts2 SET scantemplateincludingunits = "kolhydrat %f gram" WHERE id = 55;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Kolhydrat %f Gram" WHERE id = 56;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Koppar %f Kilokalori" WHERE id = 57;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Koppar %f Mikrogram" WHERE id = 58;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Koppar %f Milligram" WHERE id = 59;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Krom %f Mikrogram" WHERE id = 60;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Magnesium %f Milligram" WHERE id = 61;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Mangan %f Milligram" WHERE id = 62;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Molybden %f g" WHERE id = 63;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Molybden %f Mikrogram" WHERE id = 64;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NACL %f Gram" WHERE id = 65;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NACL %f Milligram" WHERE id = 66;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Natrium %f Gram" WHERE id = 67;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Natrium %f Milligram" WHERE id = 68;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Niacin %f Milligram" WHERE id = 69;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Pantotensyra %f mg" WHERE id = 70;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Pantotensyra %f Milligram" WHERE id = 71;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Protein %f g" WHERE id = 72;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 73;
UPDATE temporarynuts2 SET scantemplateincludingunits = "protein %f gram" WHERE id = 74;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Protein %f Gram" WHERE id = 75;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 76;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Riboflavin %f mg" WHERE id = 77;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Riboflavin %f Milligram" WHERE id = 78;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 79;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 80;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Salt %f g" WHERE id = 81;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 82;
UPDATE temporarynuts2 SET scantemplateincludingunits = "salt %f gram" WHERE id = 83;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Salt %f Gram" WHERE id = 84;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Selen %f Mikrogram" WHERE id = 85;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Tiamin %f Milligram" WHERE id = 86;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav enkelomättat fett %f g" WHERE id = 87;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Varav enkelomättat fett %f Gram" WHERE id = 88;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav fleromättat fett %f g" WHERE id = 89;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Varav fleromättat fett %f Gram" WHERE id = 90;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav laktos %f g" WHERE id = 91;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav mättat fett %f g" WHERE id = 92;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav: Mättat fett %fg  " WHERE id = 93;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav mättat fett %f gram" WHERE id = 94;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Varav mättat fett %f Gram" WHERE id = 95;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav polyoler %f gram" WHERE id = 96;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Varav polyoler %f Gram" WHERE id = 97;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 98;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 99;
UPDATE temporarynuts2 SET scantemplateincludingunits = "NULL" WHERE id = 100;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav sockerarter %f g" WHERE id = 101;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav: Sockerarter %fg  " WHERE id = 102;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav sockerarter %f gram" WHERE id = 103;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Varav sockerarter %f Gram" WHERE id = 104;
UPDATE temporarynuts2 SET scantemplateincludingunits = "varav sockerater %f g" WHERE id = 105;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Varav stärkelse %f Gram" WHERE id = 106;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin A%f µg (39% av DRI*) *Dagligt Referensintag  " WHERE id = 107;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin A %f g" WHERE id = 108;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin A %f Mikrogram" WHERE id = 109;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin B12 %f g" WHERE id = 110;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin B12 %f mg" WHERE id = 111;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin B12 %f Mikrogram" WHERE id = 112;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin B6 %f Milligram" WHERE id = 113;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin C %f mg" WHERE id = 114;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin C %f Milligram" WHERE id = 115;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin D %f g" WHERE id = 116;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin D %f Gram" WHERE id = 117;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin D %f Mikrogram" WHERE id = 118;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin E %f Milligram" WHERE id = 119;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Vitamin K %f Mikrogram" WHERE id = 120;
UPDATE temporarynuts2 SET scantemplateincludingunits = "Zink %f Milligram" WHERE id = 121;
